name: Build Hound's Hunt with Pygbag and Upload
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Hound's Hunt Web Build and Upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    - name: Build Hound's Hunt w/ Pygbag
      run: |
            python -m pip install -r requirements.txt
            python -m pygbag --ume_block 0 --build main.py
            echo "Successfully build the game and complied to WebAssembly! :)"

    - name : Upload to GitHub pages branch gh-page
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-page
        folder: build/web